MVC_Proyect/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Proyect.Models;
using Microsoft.AspNetCore.Http;

namespace MVC_Proyect.Controllers
{
    public class AccesoController : Controller
    {

//Cerrar Sesion del usuario
        public ActionResult CloseSession(){

            int id = 0;
            CookieOptions cookie = new CookieOptions();
            Response.Cookies.Append("ID", id.ToString(), cookie);
        return Redirect("/Job/ScreenPrincipalView");

        }

        public async Task<ActionResult> PosterDashboard(int id)
        {
            Offer_Job Job = new Offer_Job();
            Usuario1 user = new Usuario1();

            var users = await user.Get();
            var empleos = await Job.Get();



            var usuario = users.Where(x => x.ID == id).First();
            ViewData["Jobs"] = empleos.Where(x => x.Email == usuario.Email).ToList();
            ViewData["Poster"] = usuario;
            return View();
        }



        //Vista del Login para iniciar sesion
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        // Metodo para comprobar si x usuario existe 
        [HttpPost]
        public async Task<IActionResult> Login(Usuario1 user)
        {
            // metodo para validar
            TempData["Accion"] = await user.TryLogin();

           //Crear cookie
           int id = await user.ObtenerID();
            CookieOptions cookie = new CookieOptions();
            Response.Cookies.Append("ID", id.ToString(), cookie);

System.Console.WriteLine(id);

            return View();
        }

        // Vista para el registro 
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        // Insertar registro
        [HttpPost]
        public async Task<ActionResult> Register(Usuario1 user)
        {
            if (ModelState.IsValid)
            {
                TempData["Notificacion"] = await user.Post();
                return View();
            }

            return View(user);
        }


        /*Vista del formulario para postear el trabajo*/
        [HttpGet]
        public async Task<IActionResult> PostJob()
        {
            ViewData["Listado_Categorias"] = await LoadResource.DropDownListCategorias();
            ViewData["Listado_Provincias"] = await LoadResource.DropDownListProvincias();
            return View();
        }

        /*Postear oferta*/
        public async Task<IActionResult> PostJob(Offer_Job offer_Job)
        {
            if (ModelState.IsValid)
            {
                TempData["Notificacion"] = await offer_Job.Post();
                return View(); // donde corresponda
            }

            ViewData["Listado_Categorias"] = await LoadResource.DropDownListCategorias();
            ViewData["Listado_Provincias"] = await LoadResource.DropDownListProvincias();
            return View(offer_Job);
        }

        /*Actualizar oferta*/
        public async Task<IActionResult> PutJob(Offer_Job offer_Job)
        {
            if (ModelState.IsValid)
            {
                 TempData["Notificacion"] = await offer_Job.Put();
                return RedirectToAction(""); //donde corresponda
            }

            return RedirectToAction("PostJob", offer_Job);
        }

        /*Eliminar oferta*/
        public async Task<IActionResult> DeleteJob(Offer_Job id_oferta)
        {
            TempData["Notificacion"] = await id_oferta.Delete();
            return RedirectToAction(""); //donde corresponda
        }
      
    }

    public static class LoadResource
    {
        public static async Task<List<SelectListItem>> DropDownListCategorias()
        {
            var listadoCategorias = await new Categoria().Get();

            var dropdownListCategorias = listadoCategorias.ToList().ConvertAll(d =>
             new SelectListItem()
             {
                 Text = d.nombreCategoria,
                 Value = d.id.ToString(),
                 Selected = false
             });

            return dropdownListCategorias;
        }

        public static async Task<List<SelectListItem>> DropDownListProvincias()
        {
            var listadoProvincias = await new Provincia().Get();

            var dropdownListProvincias = listadoProvincias.ToList().ConvertAll(d =>
             new SelectListItem()
             {
                 Text = d.Nombre,
                 Value = d.Nombre.ToString(),
                 Selected = false
             });

            return dropdownListProvincias;
        }

    

    }

}

MVC_Proyect/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_Proyect.Models;
using System.Net.Http;
using Newtonsoft.Json;

namespace MVC_Proyect.Controllers
{
    public class JobController : Controller
    {
        public async Task<IActionResult> ScreenPrincipalView()
        {
            Offer_Job Job = new Offer_Job();
            var lista = await Job.Get();
            ViewData["Ciudades"] = lista.Select(x => x.Ciudad).ToList();
            ViewData["Jobs"] = lista;


            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SearchJob()
        {
            Offer_Job Job = new Offer_Job();
            var resultado = await Job.Get();
            ViewData["Ciudades"] = resultado.Select(x => x.Ciudad).ToList();
            ViewData["Jobs"] = resultado;


            return View();
        }


        [HttpPost]
        public async Task<IActionResult> SearchJob(Offer_Job job)
        {

            Offer_Job Job = new Offer_Job();
            var listado = await Job.Get();
            ViewData["Ciudades"] = listado.Select(x => x.Ciudad).ToList();

            if (job.Posicion != null)
                listado = listado.Where(x => x.Posicion == job.Posicion).ToList();

            if (job.Ciudad != "0")
                listado = listado.Where(x => x.Ciudad == job.Ciudad).ToList();

            ViewData["Jobs"] = listado;

            return View();

        }

        public IActionResult JobView()
        {
            return View();
        }

        public IActionResult CategoryView()
        {
            return View();
        }

    }
}

MVC_Proyect/Views/Acceso/Form.cshtml
@model MVC_Proyect.Models.Offer_Job


@{
    ViewData["Title"] = "Form";
}

<head>
    <link rel="stylesheet" type="text/css" href="~/css/Form_Job_Post_Style.css">
</head>

<body>

    <div class="main-container">

        <header class="header-form">
            <h1>Publicar oferta de trabajo</h1>

            <img src="https://media.istockphoto.com/vectors/working-conditions-rgb-color-icon-vector-id1273321472?k=6&m=1273321472&s=170667a&w=0&h=H7bRVD3j0LlZ5Tgm1fj_5c-EeJY49bqYFwq2vRsgQaQ="
                 alt="hombrecito">
        </header>

        <main>
            <section class="section-formulario">

                @using (Html.BeginForm("PostJob", "Acceso", FormMethod.Post))
                {
                    <div class="form-header">

                        @Html.DropDownList("Categoria", ViewData["Listado_Categorias"] as List<SelectListItem>, "Categorias")

                        <div>
                            <h2>Tipo</h2>

                            <ul class="lista-tipo">
                                <li>
                                    @Html.RadioButtonFor(o => o.Tipo, "Full-Time")
                                    <label for="male">Full-time</label>
                                </li>

                                <li>
                                    @Html.RadioButtonFor(o => o.Tipo, "Part-Time")
                                    <label for="male">Part-time</label>
                                </li>

                                <li>
                                    @Html.RadioButtonFor(o => o.Tipo, "Freelance")
                                    <label for="male">Freelance</label>
                                </li>
                            </ul>
                            <img src="https://image.flaticon.com/icons/png/512/1717/1717782.png" alt="icon-reloj">
                        </div>

                    </div>

                    <div class="form-body">

                        <div class="form-first-column">

                            <div class="form-piece-text">
                                <label class="form-label-first-column">Compañia <span class="obligatorio">*</span></label>
                                <div>
                                    @Html.TextBoxFor(o => o.Compania, null, new { @class = "form-control", placeholder = "Compañia" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/512/1962/1962551.png" alt="icon-company">
                                </div>
                            </div>

                            <div class="form-piece-text">
                                <label class="form-label-first-column">Posicion <span class="obligatorio">*</span></label>
                                <div>
                                    @Html.TextBoxFor(o => o.Posicion, null, new { Placeholder = "Posicion" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/512/535/535335.png" alt="icon-rol">
                                </div>
                            </div>

                            <div class="form-piece-text">
                                <label class="form-label-first-column">Descripcion <span class="obligatorio">*</span></label>
                                <div>
                                    @Html.TextAreaFor(o => o.Descripcion, new { @class = "form-textarea", Placeholder = "Descripcion" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/512/124/124043.png" alt="icon-pencil">
                                </div>
                            </div> <br>

                            <div class="form-piece-text">
                                <label class="form-label-first-column">Requisitos <span class="obligatorio">*</span></label>
                                <div>
                                    @Html.TextAreaFor(o => o.Requisitos, new { @class = "form-textarea", Placeholder = "Requisitos" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/128/4059/4059838.png" alt="icon-required">
                                </div>
                            </div>

                        </div>

                        <div class="form-second-column">

                            <div class="form-piece-text">
                                <label>Logotipo empresarial </label>
                                <div>
                                    @Html.TextBoxFor(o => o.Logo, new { type = "file" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/128/2345/2345409.png" alt="icon-company">
                                </div>
                            </div> <br>

                            <div class="form-piece-text">
                                <label class="form-label-second-column">Ubicacion / Direccion <span class="obligatorio">*</span></label>
                                <div>
                                    @Html.TextBoxFor(o => o.Ciudad, null, new { Placeholder = "Ciudad" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/512/1246/1246467.png" alt="icon-location">
                                </div>
                            </div>

                            <div class="form-piece-text">
                                <label class="form-label-second-column">Sitio web Empresa</label>
                                <div>
                                    @Html.TextBoxFor(o => o.Url, null, new { Placeholder = "URL" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/512/1674/1674664.png" alt="icon-web">
                                </div>
                            </div>

                            <div class="form-piece-text">
                                <label class="form-label-second-column">Correo electronico <span class="obligatorio">*</span></label>
                                <div>
                                    @Html.TextBoxFor(o => o.Email, null, new { Placeholder = "Email" }) &nbsp;&nbsp;
                                    <img src="https://i.pinimg.com/originals/80/09/29/800929944b228b1569c308b81e810b60.png" alt="icon-email">
                                </div>
                            </div>

                            <div class="form-footer">
                                <button type="submit" id="confirmar">Publicar</button>
                                <button id="cancelar" asp-controller="Job" asp-action="ScreenPrincipalView">Cancelar</button>
                            </div>

                        </div>
                    </div>

                 }

            </section>
        </main>

    </div>
</body>

MVC_Proyect/Views/Acceso/Login.cshtml
@model Usuario1

@{
    ViewData["Title"] = "Autenticacion";
}

@Html.Raw(TempData["Accion"])
  
<head>
    <link rel="stylesheet" type="text/css" href="~/css/Estilos_login.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
</head>
<body class="second-body">

    <div class="animate__animated animate__zoomInLeft" id="container">

        <main>

            <section class="img-side">
            </section>

            <section class="form-side">

                <div class="form-container">

                    <header>
                        <div>
                            <img src="~/img/burbujita.png" alt="burbuja comentario">
                        </div>
                        <img src="https://geniosconsulting.com.mx/img/equipo/7.png" alt="usuario">
                        <h1>WELCOME</h1>
                    </header>

                    @using (Html.BeginForm("Login", "Acceso", FormMethod.Post))
                    {
                        <div>
                            @Html.TextBoxFor(u => u.Username, null, new { Placeholder = "Username", Autocomplete = "off" }) &nbsp;&nbsp;
                        </div>

                        <div>
                            @Html.TextBoxFor(u => u.Contraseña, null, new { Placeholder = "Password", Type = "Password" }) &nbsp;&nbsp;
                        </div>

                        <button type="submit" name="" class="login-button">Iniciar</button>
                    }

                    <a href='@Url.Action("Register", "Acceso")'>
                    <button id="registrarse-link">Registrarse</button>
                    </a>
                </div>

            </section>

        </main>

    </div>

</body>

MVC_Proyect/Views/Acceso/PostJob.cshtml
@model MVC_Proyect.Models.Offer_Job


@{
    ViewData["Title"] = "Form";
}

@Html.Raw(ViewData["Notificacion"])

<head>
    <link rel="stylesheet" type="text/css" href="~/css/Form_Job_Post_Style.css">
</head>

<body>

    <div class="main-container">

        <header class="header-form">
            <h1>Publicar oferta de trabajo</h1>

            <img src="https://media.istockphoto.com/vectors/working-conditions-rgb-color-icon-vector-id1273321472?k=6&m=1273321472&s=170667a&w=0&h=H7bRVD3j0LlZ5Tgm1fj_5c-EeJY49bqYFwq2vRsgQaQ="
                 alt="hombrecito">
        </header>

        <main>
            <section class="section-formulario">

                @using (Html.BeginForm("PostJob", "Acceso", FormMethod.Post))
                {
                    <div class="form-header">
                        
                        @Html.DropDownListFor(x => x.Id_Categoria, ViewData["Listado_Categorias"] as List<SelectListItem>, "Categoria")

                        <div>
                            <h2>Tipo</h2>

                            <ul class="lista-tipo">
                                <li>
                                    @Html.RadioButtonFor(o => o.Tipo, "Full-Time")
                                    <label for="male">Full-time</label>
                                </li>

                                <li>
                                    @Html.RadioButtonFor(o => o.Tipo, "Part-Time")
                                    <label for="male">Part-time</label>
                                </li>

                                <li>
                                    @Html.RadioButtonFor(o => o.Tipo, "Freelance")
                                    <label for="male">Freelance</label>
                                </li>
                            </ul>
                            <img src="https://image.flaticon.com/icons/png/512/1717/1717782.png" alt="icon-reloj">
                        </div>

                    </div>

                    <div class="form-body">

                        <div class="form-first-column">

                            <div class="form-piece-text">
                                <label class="form-label-first-column">Compañia <span class="obligatorio"> @Html.ValidationMessageFor(n => n.Compania, null)</span></label>
                                <div>
                                    @Html.TextBoxFor(o => o.Compania, null, new { @class = "form-control", placeholder = "Compañia" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/512/1962/1962551.png" alt="icon-company">
                                </div>
                            </div>

                            <div class="form-piece-text">
                                <label class="form-label-first-column">Posicion <span class="obligatorio"> @Html.ValidationMessageFor(n => n.Posicion, null)</span></label>
                                <div>
                                    @Html.TextBoxFor(o => o.Posicion, null, new { Placeholder = "Posicion" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/512/535/535335.png" alt="icon-rol">
                                </div>
                            </div>

                            <div class="form-piece-text">
                                <label class="form-label-first-column">Descripcion <span class="obligatorio"> @Html.ValidationMessageFor(n => n.Descripcion, null)</span></label>
                                <div>
                                    @Html.TextAreaFor(o => o.Descripcion, new { @class = "form-textarea", Placeholder = "Descripcion" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/512/124/124043.png" alt="icon-pencil">
                                </div>
                            </div> <br>

                                   <div class="form-piece-text">
                                       <label class="form-label-first-column">Requisitos <span class="obligatorio"> @Html.ValidationMessageFor(n => n.Requisitos, null)</span></label>
                                       <div>
                                           @Html.TextAreaFor(o => o.Requisitos, new { @class = "form-textarea", Placeholder = "Requisitos" }) &nbsp;&nbsp;
                                           <img src="https://image.flaticon.com/icons/png/128/4059/4059838.png" alt="icon-required">
                                       </div>
                                   </div>
                        </div>

                        <div class="form-second-column">

                            <div class="form-piece-text">
                                <label>Logotipo empresarial </label>
                                <div>
                                    @Html.TextBoxFor(o => o.Logo, new { type = "file" }) &nbsp;&nbsp;
                                    <img src="https://image.flaticon.com/icons/png/128/2345/2345409.png" alt="icon-company">
                                </div>
                            </div> <br>

                                   <div class="form-piece-text">
                                       <label class="form-label-second-column">Provincia / Ubicacion <span class="obligatorio"> @Html.ValidationMessageFor(n => n.Ciudad, null)</span></label>
                                       <div>
                                           @Html.DropDownListFor(o => o.Ciudad, ViewData["Listado_Provincias"] as List<SelectListItem>, "Provincia") &nbsp;&nbsp;
                                           <img src="https://image.flaticon.com/icons/png/512/1246/1246467.png" alt="icon-location">
                                       </div>
                                   </div>

                                   <div class="form-piece-text">
                                       <label class="form-label-second-column">Sitio web Empresa</label>
                                       <div>
                                           @Html.TextBoxFor(o => o.Url, null, new { Placeholder = "URL" }) &nbsp;&nbsp;
                                           <img src="https://image.flaticon.com/icons/png/512/1674/1674664.png" alt="icon-web">
                                       </div>
                                   </div>

                                   <div class="form-piece-text">

                                       <label class="form-label-second-column">Correo electronico <span class="obligatorio"> @Html.ValidationMessageFor(n => n.Email, null)</span></label>
                                       <div>
                                           @Html.TextBoxFor(o => o.Email, null, new { Placeholder = "Email" }) &nbsp;&nbsp;
                                           <img src="https://i.pinimg.com/originals/80/09/29/800929944b228b1569c308b81e810b60.png" alt="icon-email">
                                       </div>
                                   </div>
                            <input type="text" name="Fecha" value="@DateTime.Now" hidden="hidden">

                            <div class="form-footer">
                                <button type="submit" id="confirmar">Publicar</button>
                                <button id="cancelar" asp-controller="Job" asp-action="ScreenPrincipalView">Cancelar</button>
                            </div>

                        </div>
                    </div>

                }

            </section>
        </main>

    </div>
</body>

MVC_Proyect/Views/Acceso/PosterDashboard.cshtml
@{
    ViewData["Title"] = "PosterDashboard";
    var empleos = ViewData["Jobs"] as List<Offer_Job>;
    var usuario = ViewData["Poster"] as Usuario1;
}

<head>
    <link rel="stylesheet" href="~/css/PosterDashboard.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet">
</head>

    <section class="poster-main">
        <div class="poster-information">
            <h1>@usuario.Nombre @usuario.Apellido</h1>
            <p><i>@usuario.Url</i></p>
        </div>

        <div class="poster-post-count">
            <p>Ofertas Publicadas:</p>
            <p class="post-number">@empleos.Count</p>
        </div>
    </section>

    <section class="post-posted">
        <h2>Ofertas Posteadas:</h2>

        <div class="job-list">

@if(empleos.Count > 0){
@foreach (var job in empleos){

            <div class="job">
                <div class="job-header">
                    <img src="~/img/defaultwork.svg" alt="" width="90px">

                    <div>
                        <br>
                        <h2>@job.Posicion</h2>
                        <br> <br>
                        <p><strong>Ciudad: </strong>@job.Ciudad&nbsp;&nbsp;&nbsp;&nbsp;</p>
                        <p><strong>Sueldo: </strong>A discutir</p>
                    </div>
                </div>

                <div class="job-body">
                    <p>@job.Descripcion</p>
                </div>

                <a href="" class="job-end rojo">Eliminar</a>
            </div>
 }
}
        </div>

        @if(empleos.Count == 0){
    <p class="no-offer">Aun no ha publicado ninguna oferta!! </p>
}

<div class="logout">
      <a asp-controller="Acceso" asp-action="CloseSession">
           Cerrar Sesion
      </a>
   
</div>

    </section>
   

MVC_Proyect/Views/Acceso/Register.cshtml
@model Usuario1

@{
    ViewData["Title"] = "Register";
}

@Html.Raw(TempData["Notificacion"])

<head>
    <title>Registro</title>
    <link rel="stylesheet" type="text/css" href="~/css/Register_login.css">
</head>
<body class="second-body">

    <div class="container">

        <main>

            <section class="img-side">
                <img src="~/img/munequita.jpg">
            </section>

            <section class="form-side">

                <div class="form-container">

                    <header>
                        <div>
                            <h1>Regístrate</h1>
                            <p>Hazlo para ofrecer ofertas y <br /> nuevas oportunidades de empleo</p>
                        </div>

                        <div>
                            <img src="https://image.flaticon.com/icons/png/128/3534/3534139.png">
                        </div>
                    </header>

                    @using (Html.BeginForm("Register", "Acceso", FormMethod.Post))
                    {

                        <div class="form-text-piece">
                            <div>
                                <label>Nombre</label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.ValidationMessageFor(n => n.Nombre, null, new { @class = "text-danger" })
                            </div>
                            @Html.TextBoxFor(u => u.Nombre, null, new { Autocomplete = "off" })
                        </div>

                        <div class="form-text-piece">
                            <div>
                                <label>Apellido</label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.ValidationMessageFor(n => n.Apellido, null, new { @class = "text-danger" })
                            </div>
                            @Html.TextBoxFor(u => u.Apellido, null, new { Autocomplete = "off" })
                        </div>

                        <div class="form-text-piece">
                            <div>
                                <label>Email personal</label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.ValidationMessageFor(n => n.Email, null, new { @class = "text-danger" })
                            </div>
                            @Html.TextBoxFor(u => u.Email, null, new { Autocomplete = "off" })
                        </div>

                        <div class="form-text-piece">
                            <div>
                                <label>Email de empresa</label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.ValidationMessageFor(n => n.Email_emp, null, new { @class = "text-danger" })
                            </div>
                            @Html.TextBoxFor(u => u.Email_emp, null, new { Autocomplete = "off" })
                        </div>

                        <div class="form-text-piece">
                            <label>URL empresa <span class="sugerencia">&nbsp;&nbsp;&nbsp;(opcional)</span></label>
                            <div>
                                @Html.TextBoxFor(u => u.Url, null, new { Autocomplete = "off" }) &nbsp;&nbsp;
                            </div>
                        </div>

                        <div class="form-text-piece">
                            <div>
                                <label>Telefono</label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.ValidationMessageFor(n => n.Telefono, null, new { @class = "text-danger" })
                            </div>
                            @Html.TextBoxFor(u => u.Telefono, string.Empty, new { Autocomplete = "off" }) &nbsp;&nbsp;
                        </div>

                        <div class="form-text-piece">
                            <div>
                                <label>Nombre de Usuario <span class="sugerencia">&nbsp;&nbsp;(recordar)</label> &nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.ValidationMessageFor(n => n.Username, null, new { @class = "text-danger" })
                            </div>
                            @Html.TextBoxFor(u => u.Username, null, new { Autocomplete = "off" }) &nbsp;&nbsp;
                        </div>

                        <div class="form-text-piece">
                            <div>
                                <label>Contraseña <span class="sugerencia">&nbsp;&nbsp;&nbsp;(recordar)</label> &nbsp;&nbsp;&nbsp;&nbsp;
                                @Html.ValidationMessageFor(n => n.Contraseña, null, new { @class = "text-danger" })
                            </div>
                            @Html.TextBoxFor(u => u.Contraseña, null, new { Autocomplete = "off" }) &nbsp;&nbsp;
                        </div>
                        <input type="text" name="Rol" value="Poster" hidden="hidden"> //Rol por defecto del usuario que se registra (no cambiar) !
                        <div>
                            <button type="submit" id="registrarse-btn">Listo</button>
                        </div>
                    }
                </div>

            </section>

        </main>

    </div>

</body>